- name: Tap homebrew cask
  tags:
    - homebrew
    - homebrew-cask
  homebrew_tap: tap=caskroom/cask state=present

- name: Update homebrew
  tags:
    - homebrew
    - homebrew-cask
  homebrew: update_homebrew=yes

- name: Tap cask repositories
  tags:
    - homebrew
    - homebrew-cask
  homebrew_tap: tap={{ item }} state=present
  with_items: "{{homebrew_cask_repositories}}"
  when: homebrew_cask_repositories

- name: Install/Upgrade cask packages
  tags:
    - homebrew
    - homebrew-cask
  homebrew_cask: >
    name={{ item.name | default(item) }}
    state={{ item.state | default('present') }}
  with_items: "{{homebrew_cask_packages}}"
  when: homebrew_cask_packages
  register: homebrew_cask_results

- name: brew infoを記録するディレクトリ作成
  tags:
    - homebrew
    - homebrew-cask
  file: path={{brew_cask_info_dir}} state=directory

- name: brew infoを記録
  tags:
    - homebrew
    - homebrew-cask
  shell: brew cask info {{item}} > {{brew_cask_info_dir}}/{{item}}
  with_items: "{{homebrew_cask_results.results | selectattr('changed') | map(attribute='item') | list}}"
