- name: Tap sanemat/font
  tags:
    - font
    - font-ricty
  homebrew_tap: tap=sanemat/font state=present

- name: Get Ricty by homebrew
  tags:
    - font
    - font-ricty
  homebrew: name=ricty state=latest
  register: get_ricty

- name: インストールのコマンドを取得
  tags:
    - font
    - font-ricty
  shell: brew info ricty | grep '\$' | sed -e 's/  \$ //'
  register: ricty_install_commands

- name: Install Ricty
  tags:
    - font
    - font-ricty
  shell: "{{item}}"
  with_items: "{{ricty_install_commands.stdout_lines}}"
  when: get_ricty | changed and ricty_install_commands | changed
