- name: homebrewでinstall
  tags:
    - zsh
    - homebrew
    - homebrew-base
  homebrew: name={{item}} state=latest
  with_items:
    - zsh
    - reattach-to-user-namespace
    - tmux
    - z

- name: Pull dotfiles
  tags:
    - zsh
    - dotfiles
  git: repo={{dotfiles_repo}} dest={{dotfiles_dir}}
    accept_hostkey=yes
    force=yes
  register: pull_dotfiles

- name: init.shを+xに
  tags:
    - zsh
    - dotfiles
  file: path={{dotfiles_dir}}/init.sh mode=a+x
  when: pull_dotfiles | changed

- name: Init dotfiles
  tags:
    - zsh
    - dotfiles
  shell: ./init.sh
    chdir={{dotfiles_dir}}
  when: pull_dotfiles | changed

- name: /etc/shellsにpath追加
  tags:
    - zsh
  become: true
  lineinfile: dest=/etc/shells state=present
    regexp="^{{zsh_path}}$"
    line="{{zsh_path}}"

- name: chshでログインシェル変更
  tags:
    - zsh
  become: true
  shell: chsh -s {{zsh_path}}
