- name: homebrewでinstall
  tags:
    - zsh
    - homebrew
    - homebrew-base
  homebrew: >
    name={{ item.name | default(item) }}
    state={{ item.state | default('latest') }}
    install_options={{
      item.install_options | default() | join(',')
      if item.install_options is not string
      else item.install_options
    }}
  with_items:
    - {name: zsh, install_options: disable-etcdir}
    - reattach-to-user-namespace
    - tmux
    - z

- name: Pull dotfiles
  tags:
    - zsh
    - dotfiles
  git: repo={{dotfiles_repo}} dest={{dotfiles_dir}}
    accept_hostkey=yes
    force=yes
  register: pull_dotfiles

- name: init.shを+xに
  tags:
    - zsh
    - dotfiles
  file: path={{dotfiles_dir}}/init.sh mode=a+x
  when: pull_dotfiles | changed

- name: Init dotfiles
  tags:
    - zsh
    - dotfiles
  shell: ./init.sh
    chdir={{dotfiles_dir}}
  when: pull_dotfiles | changed

- name: /etc/shellsにpath追加
  tags:
    - zsh
  become: true
  lineinfile: dest=/etc/shells state=present
    regexp="^{{zsh_path}}$"
    line="{{zsh_path}}"
  register: etc_shells

- name: chshでログインシェル変更
  tags:
    - zsh
  shell: chsh -s {{zsh_path}}
  when: etc_shells | changed
