- name: Tap repositories
  tags:
    - homebrew
    - homebrew-base
  homebrew_tap: tap={{ item }} state=present
  with_items: "{{homebrew_repositories}}"
  when: homebrew_repositories

- name: Update homebrew
  tags:
    - homebrew
    - homebrew-base
  homebrew: update_homebrew=yes

- name: Install/Upgrade packages
  tags:
    - homebrew
    - homebrew-base
  homebrew: >
    name={{ item.name | default(item) }}
    state={{ item.state | default('latest') }}
    install_options={{
      item.install_options | default() | join(',')
      if item.install_options is not string
      else item.install_options
    }}
  with_items: "{{homebrew_packages}}"
  when: homebrew_packages
  register: homebrew_results

- name: brew infoを記録するディレクトリ作成
  tags:
    - homebrew
    - homebrew-base
  file: path={{brew_info_dir}} state=directory

- name: brew infoを記録
  tags:
    - homebrew
    - homebrew-base
  shell: brew info {{item}} > {{brew_info_dir}}/{{item}}
  with_items: "{{homebrew_results.results | selectattr('changed') | map(attribute='item') | list}}"
