- name: Install dependent packages
  tags:
    - ruby
    - rbenv
  homebrew: name={{item}} state=latest
  with_items:
    - openssl
    - readline
  register: install_dependent_packages

- name: Link libraries
  tags:
    - ruby
    - rbenv
  homebrew: name={{item}} state=linked install_options=force
  with_items:
    - openssl
  when: install_dependent_packages | changed

- name: Install rbenv
  tags:
    - ruby
    - rbenv
  homebrew: name={{item}} state=latest
  with_items:
    - rbenv
    - ruby-build
  register: install_rbenv

- name: Init rbenv
  tags:
    - ruby
    - rbenv
  shell: eval "$(rbenv init -)"
  when: install_rbenv | changed

- name: Install latest version of ruby
  tags:
    - ruby
    - rbenv
  shell: rbenv install -s $(rbenv install -l | grep -v - | tail -1)
  register: install_ruby
  changed_when: '"Installed ruby" in install_ruby.stderr'

- name: Set rbenv global
  tags:
    - ruby
    - rbenv
  shell: rbenv global $(rbenv install -l | grep -v - | tail -1)
  when: install_ruby | changed

- name: Install bundler gem
  tags:
    - ruby
    - rbenv
  gem: name=bundler state=latest
