- name: Install dependent packages
  tags:
    - ruby
    - rbenv
  homebrew: >
    name={{ item.name | default(item) }}
    state={{ item.state | default('latest') }}
    install_options={{
      item.install_options | default() | join(',')
      if item.install_options is not string
      else item.install_options
    }}
  with_items:
    - openssl
    - {name: openssl, state: linked, install_options: force}
    - readline
    - rbenv
    - ruby-build

- name: Install rbenv
  tags:
    - ruby
    - rbenv
  homebrew: >
    name={{ item.name | default(item) }}
    state={{ item.state | default('latest') }}
  with_items:
    - rbenv
    - ruby-build
  register: install_rbenv

- name: Init rbenv
  tags:
    - ruby
    - rbenv
  shell: eval "$(rbenv init -)"
  when: install_rbenv | changed

- name: Install latest version of ruby
  tags:
    - ruby
    - rbenv
  shell: rbenv install -s $(rbenv install -l | grep -v - | tail -1)
  register: install_ruby_versions
  changed_when: '"Installed ruby" in install_ruby_versions.stderr'

- name: Set rbenv global
  tags:
    - ruby
    - rbenv
  shell: rbenv global $(rbenv install -l | grep -v - | tail -1)
  when: install_ruby_versions | changed

- name: Install bundler gem
  tags:
    - ruby
    - rbenv
  gem: name=bundler state=latest
  when: install_ruby_versions | changed
